use customer_behavior;
select * FROM customer_data;

-- What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) as revenue
from customer_data group by gender;

-- Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount from customer_data
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customer_data);

-- Which are the top 5 products with the highest average review rating?
SELECT item_purchased, avg(review_rating) as "Average Producr Rating"
from customer_data
group by item_purchased
order by avg(review_rating) desc
limit 5 ; 

-- Compare the average purchase amounts between Standard and Express Shipping.
SELECT shipping_type, round(avg(purchase_amount),2) as "avg_purchase_amount"
from customer_data
where shipping_type in ("Standard","Express")
group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, count(customer_id) as "total_customer",
avg(purchase_amount) as "avg_spend",
sum(purchase_amount) as "total_revenue"
from customer_data
group by subscription_status
order by total_revenue desc, avg_spend desc;

-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
round(sum(case WHEN discount_applied = "Yes" Then 1 Else 0 END ) * 100/COUNT(*) ,2) AS "discount_rate"
from customer_data
group by item_purchased	
order by discount_rate desc
limit 5 ;

-- Segment customers into New, Returning, and Loyal based on their 
-- total number of previous purchases, and show the count of each segment.

SELECT 
    CASE 
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS total_customers

FROM customer_data
GROUP BY customer_segment
ORDER BY total_customers DESC;

-- What are the top 3 most purchased products within each category?
SELECT category, item_purchased, total_purchases
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        
        RANK() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rank_in_category
        
    FROM customer_data
    GROUP BY category, item_purchased
) ranked

WHERE rank_in_category <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repat_buyer
from customer_data 
where previous_purchases>5
group by subscription_status;

-- What is the revenue contribution of each age group?
SELECT age_group,
sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue desc;